### ISSUE TITLE
一年读这么多

### ISSUE THREAD

**Issue by jinguoliang** [ruanyf/reading-list#5]
您好，一直觉得你的博客很好，也知道您是那种能沉住气一步一步往前走的人，但是我不明白为什么你一年能读这么多书，因为我读书挺慢的。

**Comment by ruanyf** [comment]
不是每本书都需要精读的，有的书精读几个章节即可。

**Comment by jinguoliang** [comment]
谢谢，明白了，我一直都是没有选择的一个字的读，还是要有选择
